name: cartokit CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
      - name: Install root dependencies
        run: pnpm install --frozen-lockfile
      - name: Install docs dependencies
        run: cd docs && pnpm install --frozen-lockfile && cd ..
      - name: Build cartokit docs
        run: cd docs && pnpm build && cd ..
      - name: Lint
        run: pnpm lint
